[package]
name = "annotate"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
crossterm = { version = "0.28.1", features = ["event-stream"] }
csv = "1.3.1"
futures = "0.3.31"
lib = { path = "../lib" }
tokio = "1.43.0"
